version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

volumes:
  mongo_data: