apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        command: ["sh", "-c", "cp /backup/restore-mongo.sh /tmp/restore-mongo.sh && chmod +x /tmp/restore-mongo.sh && /tmp/restore-mongo.sh && docker-entrypoint.sh mongod"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: backup-storage
          mountPath: /backup
        - name: restore-script
          mountPath: /backup/restore-mongo.sh
          subPath: restore-mongo.sh
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: backup-storage
        persistentVolumeClaim:
          claimName: mongo-backup-pvc
      - name: restore-script
        configMap:
          name: restore-script
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb