symptoms = [
  {'id': 1, 'name': 'Silna potrzeba wypicia z tendencją do natychmiastowego zrealizowania'}, 
  {'id': 2, 'name': 'Uczucie monotonii'}, 
  {'id': 3, 'name': 'Uczucie ssania w źołądku'},
  {'id': 4, 'name': 'Uczucie braku czegoś'}, 
  {'id': 5, 'name': 'Sny alkoholowe'}, 
  {'id': 6, 'name': 'Suchy kac'}, 
  {'id': 7, 'name': 'Smak, zapach alkoholu gdy go nie ma'}, 
  {'id': 8, 'name': 'Stany depresyjne'}, 
  {'id': 9, 'name': 'Lęk'}, 
  {'id': 10, 'name': 'Ucuczie stałego napięcia i rozdrażnienia'},
  {'id': 11, 'name': 'Pogorszenie pamięci i koncentracji'},
  {'id': 12, 'name': 'Dokuczający stres'}, 
  {'id': 13, 'name': 'Natrętne myśli o alkoholu'},
  {'id': 14, 'name': 'Przypomnienie sobie przyjemnego stanu po alkoholu'},
  {'id': 15, 'name': 'Apatia, zobojętnienie'}, 
  {'id': 16, 'name': 'Ból'}, 
  {'id': 17, 'name': 'Znudzenie'}, 
 {'id': 18, 'name':  'Zwiększona liczba konfliktów'},
  {'id': 19, 'name': 'Nadpobudliwość'},
  {'id': 20, 'name': 'Zwątpienie w wartość trzeźwego życia'},
  {'id': 21, 'name': 'Zaburzenia snu'},
  {'id': 22, 'name': 'Skoki napięcia'},
  {'id': 23, 'name': 'Rozpamiętywanie, rozzalenie'}, 
  {'id': 24, 'name': 'Powątpiewanie w terapię'}, 
  {'id': 25, 'name': 'Porównywanie się do innych'},
  {'id': 26, 'name': 'Przeźywanie swojego źycia jako chronicznie frustrującego'}, 
  {'id': 27, 'name': 'Euforia'}
]